using System.Net;
using NUnit.Framework;
using RestSharp;
using Should.Core.Exceptions;

namespace Should.Extensions.RestSharp.UnitTests.StatusCodes
{
    [TestFixture]
    public class ShouldBeRedirectTests
    {
        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, true)]
        [TestCase(HttpStatusCode.MultipleChoices, true)]
        [TestCase(HttpStatusCode.Moved, true)]
        [TestCase(HttpStatusCode.MovedPermanently, true)]
        [TestCase(HttpStatusCode.Found, true)]
        [TestCase(HttpStatusCode.Redirect, true)]
        [TestCase(HttpStatusCode.RedirectMethod, true)]
        [TestCase(HttpStatusCode.SeeOther, true)]
        [TestCase(HttpStatusCode.NotModified, true)]
        [TestCase(HttpStatusCode.UseProxy, true)]
        [TestCase(HttpStatusCode.Unused, true)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, true)]
        [TestCase(HttpStatusCode.TemporaryRedirect, true)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeRedirectCheck(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeRedirection());
            else
            {
                var exception = Assert.Catch(() => response.ShouldBeRedirection());

                exception.ShouldNotBeNull();
                exception.ShouldImplement<AssertException>();
            }
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, true)]
        [TestCase(HttpStatusCode.MultipleChoices, true)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeAmbiguous(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeAmbiguous());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeAmbiguous());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, true)]
        [TestCase(HttpStatusCode.MultipleChoices, true)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeMultipleChoices(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeMultipleChoices());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeMultipleChoices());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, true)]
        [TestCase(HttpStatusCode.MovedPermanently, true)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeMoved(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeMoved());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeMoved());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, true)]
        [TestCase(HttpStatusCode.MovedPermanently, true)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeMovedPermanently(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeMovedPermanently());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeMovedPermanently());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, true)]
        [TestCase(HttpStatusCode.Redirect, true)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeFound(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeFound());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeFound());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, true)]
        [TestCase(HttpStatusCode.Redirect, true)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeRedirect(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeRedirect());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeRedirect());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, true)]
        [TestCase(HttpStatusCode.SeeOther, true)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeRedirectMethod(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeRedirectMethod());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeRedirectMethod());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, true)]
        [TestCase(HttpStatusCode.SeeOther, true)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeSeeOther(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeSeeOther());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeSeeOther());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, true)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeNotModified(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeNotModified());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeNotModified());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, true)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeUseProxy(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeUseProxy());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeUseProxy());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, true)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, false)]
        [TestCase(HttpStatusCode.TemporaryRedirect, false)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeUnused(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeUnused());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeUnused());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, true)]
        [TestCase(HttpStatusCode.TemporaryRedirect, true)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeRedirectKeepVerb(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeRedirectKeepVerb());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeRedirectKeepVerb());
        }

        [TestCase(HttpStatusCode.Continue, false)]
        [TestCase(HttpStatusCode.SwitchingProtocols, false)]
        [TestCase(HttpStatusCode.OK, false)]
        [TestCase(HttpStatusCode.Created, false)]
        [TestCase(HttpStatusCode.Accepted, false)]
        [TestCase(HttpStatusCode.NonAuthoritativeInformation, false)]
        [TestCase(HttpStatusCode.NoContent, false)]
        [TestCase(HttpStatusCode.ResetContent, false)]
        [TestCase(HttpStatusCode.PartialContent, false)]
        [TestCase(HttpStatusCode.Ambiguous, false)]
        [TestCase(HttpStatusCode.MultipleChoices, false)]
        [TestCase(HttpStatusCode.Moved, false)]
        [TestCase(HttpStatusCode.MovedPermanently, false)]
        [TestCase(HttpStatusCode.Found, false)]
        [TestCase(HttpStatusCode.Redirect, false)]
        [TestCase(HttpStatusCode.RedirectMethod, false)]
        [TestCase(HttpStatusCode.SeeOther, false)]
        [TestCase(HttpStatusCode.NotModified, false)]
        [TestCase(HttpStatusCode.UseProxy, false)]
        [TestCase(HttpStatusCode.Unused, false)]
        [TestCase(HttpStatusCode.RedirectKeepVerb, true)]
        [TestCase(HttpStatusCode.TemporaryRedirect, true)]
        [TestCase(HttpStatusCode.BadRequest, false)]
        [TestCase(HttpStatusCode.Unauthorized, false)]
        [TestCase(HttpStatusCode.PaymentRequired, false)]
        [TestCase(HttpStatusCode.Forbidden, false)]
        [TestCase(HttpStatusCode.NotFound, false)]
        [TestCase(HttpStatusCode.MethodNotAllowed, false)]
        [TestCase(HttpStatusCode.NotAcceptable, false)]
        [TestCase(HttpStatusCode.ProxyAuthenticationRequired, false)]
        [TestCase(HttpStatusCode.RequestTimeout, false)]
        [TestCase(HttpStatusCode.Conflict, false)]
        [TestCase(HttpStatusCode.Gone, false)]
        [TestCase(HttpStatusCode.LengthRequired, false)]
        [TestCase(HttpStatusCode.PreconditionFailed, false)]
        [TestCase(HttpStatusCode.RequestEntityTooLarge, false)]
        [TestCase(HttpStatusCode.RequestUriTooLong, false)]
        [TestCase(HttpStatusCode.UnsupportedMediaType, false)]
        [TestCase(HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [TestCase(HttpStatusCode.ExpectationFailed, false)]
        //[TestCase(HttpStatusCode.UpgradeRequired, false, false)]
        [TestCase(HttpStatusCode.InternalServerError, false)]
        [TestCase(HttpStatusCode.NotImplemented, false)]
        [TestCase(HttpStatusCode.BadGateway, false)]
        [TestCase(HttpStatusCode.ServiceUnavailable, false)]
        [TestCase(HttpStatusCode.GatewayTimeout, false)]
        [TestCase(HttpStatusCode.HttpVersionNotSupported, false)]
        public void ShouldPassShouldBeTemporaryRedirect(HttpStatusCode status, bool shouldPass)
        {
            var response = new RestResponse { StatusCode = status };

            if (shouldPass)
                Assert.DoesNotThrow(() => response.ShouldBeTemporaryRedirect());
            else
                Assert.Throws<EqualException>(() => response.ShouldBeTemporaryRedirect());
        }
    }
}
